// <auto-generated />
using System;
using MJ_APIBurger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MJ_APIBurger.Migrations
{
    [DbContext(typeof(BurgersPromosContext))]
    [Migration("20240602232203_IgnoreExistingBurgerTable")]
    partial class IgnoreExistingBurgerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MJ_APIBurger.Data.Models.MJBurger", b =>
                {
                    b.Property<int>("MJBurgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MJBurgerId"));

                    b.Property<string>("MJName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MJPrecio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("MJWithCheese")
                        .HasColumnType("bit");

                    b.HasKey("MJBurgerId");

                    b.ToTable("Burger", (string)null);
                });

            modelBuilder.Entity("MJ_APIBurger.Data.Models.MJPromo", b =>
                {
                    b.Property<int>("MJPromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MJPromoId"));

                    b.Property<int>("MJBurgerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MJFechaPromocion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MJPromoDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MJPromoId");

                    b.HasIndex(new[] { "MJBurgerId" }, "IX_Promo_BurgerId");

                    b.ToTable("Promo", (string)null);
                });

            modelBuilder.Entity("MJ_APIBurger.Data.Models.MJPromo", b =>
                {
                    b.HasOne("MJ_APIBurger.Data.Models.MJBurger", "MJBurger")
                        .WithMany("MJPromos")
                        .HasForeignKey("MJBurgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MJBurger");
                });

            modelBuilder.Entity("MJ_APIBurger.Data.Models.MJBurger", b =>
                {
                    b.Navigation("MJPromos");
                });
#pragma warning restore 612, 618
        }
    }
}
